### ISSUE TITLE
Рекомендация

### ISSUE THREAD

**Issue by baroleg** [SevaZimov/DigitalFaculty#1]
https://github.com/SevaZimov/DigitalFaculty/blob/8e64357bf08ff919aafe801aab146cfd47435992/lab1/index.html#L41

Рекомендую размещать изображения в отдельной директории, чтобы была структура. Как пример: 
https://htmlbook.ru/files/images/content/002_2.gif

**Comment by SevaZimov** [comment]
Сделано
